name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21' # 使用するJavaのバージョンを指定

    - name: Build with Gradle
      run: ./gradle build

    - name: Run tests
      run: ./gradlew test
