name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - name: Setup Gradle 8.10
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10"
      - name: Build with Gradle 8.10
        run: gradle build
        working-directory: part1

      - name: Show Test Results
        if: always() # Ensure this runs even if the build fails
        run: |
          echo "Displaying Test Results..."
          cat part1/build/reports/tests/test/index.html || true
